In [8]:
import pandas as pd

x=pd.read_csv("/content/x_train.csv")
y=pd.read_csv("/content/y_train.csv")
x_test=pd.read_csv("/content/x_test.csv")
sub=pd.read_csv("/content/sample_submission.csv")
x

,food_category,food_department,food_family,store_sales(in millions),store_cost(in millions),unit_sales(in millions),promotion_name,sales_country,marital_status,gender,...,store_sqft,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,media_type
0,Breakfast Foods,Frozen Foods,Food,4.89,1.9071,3.0,Sales Days,USA,S,M,...,30268.0,22063.0,4923.0,3282.0,0.0,0.0,0.0,0.0,0.0,Bulk Mail
1,Vegetables,Produce,Food,3.14,1.4130,2.0,Price Winners,Mexico,S,M,...,23593.0,17475.0,3671.0,2447.0,0.0,0.0,0.0,0.0,0.0,Cash Register Handout
2,Dairy,Dairy,Drink,4.20,1.3440,3.0,Price Slashers,USA,S,M,...,39696.0,24390.0,9184.0,6122.0,0.0,0.0,1.0,1.0,0.0,"Sunday Paper, Radio, TV"
3,Dairy,Dairy,Food,9.87,4.4415,3.0,Price Savers,USA,S,F,...,20319.0,16232.0,2452.0,1635.0,0.0,0.0,0.0,0.0,0.0,Product Attachment
4,Dairy,Dairy,Food,7.20,2.3760,4.0,You Save Days,USA,S,M,...,23688.0,15337.0,5011.0,3340.0,1.0,1.0,1.0,1.0,1.0,Bulk Mail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42294,Paper Products,Household,Non-Consumable,13.28,4.7808,4.0,Two Day Sale,USA,M,M,...,21215.0,13305.0,4746.0,3164.0,1.0,0.0,0.0,0.0,0.0,Radio
42295,Magazines,Periodicals,Non-Consumable,4.26,1.7040,2.0,Free For All,USA,S,F,...,20319.0,16232.0,2452.0,1635.0,0.0,0.0,0.0,0.0,0.0,"Sunday Paper, Radio"
42296,Snack Foods,Snack Foods,Food,7.88,2.9944,4.0,Bye Bye Baby,Canada,M,M,...,23112.0,16418.0,4016.0,2678.0,1.0,1.0,1.0,1.0,1.0,Sunday Paper
42297,Bathroom Products,Health and Hygiene,Non-Consumable,7.14,3.2844,3.0,Two Day Sale,USA,S,M,...,21215.0,13305.0,4746.0,3164.0,1.0,0.0,0.0,0.0,0.0,Radio
42298,Electrical,Household,Non-Consumable,7.48,3.2912,4.0,You Save Days,USA,M,F,...,20319.0,16232.0,2452.0,1635.0,0.0,0.0,0.0,0.0,0.0,TV

In [10]:
def Label(df):
  from sklearn.preprocessing import LabelEncoder
  encoder = LabelEncoder()
  for i in df:
    df[i] = encoder.fit_transform(df[i])

In [15]:
Label(x)
Label(x_test)
x

,food_category,food_department,food_family,store_sales(in millions),store_cost(in millions),unit_sales(in millions),promotion_name,sales_country,marital_status,gender,...,store_sqft,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,media_type
0,4,12,1,368,3107,2,31,2,1,1,...,11,12,9,9,0,0,0,0,0,0
1,44,17,1,233,2115,1,29,1,1,1,...,4,8,2,2,0,0,0,0,0,1
2,17,9,0,317,1977,2,27,2,1,1,...,19,16,19,19,0,0,1,1,0,11
3,17,9,1,682,7273,2,26,2,1,0,...,0,5,0,0,0,0,0,0,0,6
4,17,9,1,523,4039,3,48,2,1,1,...,6,4,10,10,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42294,35,14,2,844,7644,3,43,2,0,1,...,1,0,7,7,1,0,0,0,0,7
42295,30,16,2,322,2710,1,14,2,1,0,...,0,5,0,0,0,0,0,0,0,10
42296,41,19,1,573,5156,3,5,0,0,1,...,3,6,3,3,1,1,1,1,1,9
42297,1,13,2,518,5641,2,43,2,1,1,...,1,0,7,7,1,0,0,0,0,7
42298,21,14,2,544,5656,3,48,2,0,0,...,0,5,0,0,0,0,0,0,0,12

In [22]:
# 정확도 별로 안높음

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(x,y)
pred = model.predict(x_test)

#print(model.score(x,y))
pred

array([[ 96.72633049],
       [ 99.8232076 ],
       [ 96.55006099],
       ...,
       [ 94.24395641],
       [ 98.42501822],
       [102.66471714]])

In [ ]:
# 0.9472
import xgboost

model = xgboost.XGBRegressor(max_depth=13,n_estimators=90,learning_rate=0.5)
model.fit(x,y)
pred = model.predict(x_test)

pred

In [49]:
# 측정 안해봄
import xgboost

model = xgboost.XGBRegressor(max_depth=13,n_estimators=240,learning_rate=0.45)
model.fit(x,y)
pred = model.predict(x_test)

pred

[04:12:15] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

array([ 79.935715, 131.93353 , 142.56737 , ..., 116.39859 , 133.41562 ,
       140.19373 ], dtype=float32)

In [50]:
sub["cost"] = pred
sub
sub.to_csv("sub.csv",index=False)