In [74]:
def Df_Trans(df):
  from sklearn.preprocessing import LabelEncoder
  le = LabelEncoder()
  for key in df.keys():
    df[key] = le.fit_transform(df[key])

  #print(le.classes_)
  return df

In [75]:
import pandas as pd

data = pd.read_csv("/content/train_set.csv")
y = data["lumpy"]
del data["lumpy"]
x = data
#x=x.dropna()
#del x["reportingDate"]
#del x["country"]
#del x["region"]
x=Df_Trans(x)
x

,x,y,region,country,reportingDate,cld,dtr,frs,pet,pre,tmn,tmp,tmx,vap,wet,elevation,dominant_land_cover,X5_Ct_2010_Da,X5_Bf_2010_Da
0,0,937,3,18,302,585,49,235,0,454,309,311,310,20,1166,69,3,0,9358
1,0,938,3,18,302,604,50,235,0,447,301,303,303,18,1232,69,3,0,8937
2,0,939,3,18,302,632,55,235,0,428,285,290,292,16,1519,80,3,0,9519
3,0,940,3,18,302,657,56,235,0,417,277,282,285,16,1489,85,3,0,8287
4,0,941,3,18,302,700,58,235,0,389,265,271,275,15,1532,82,9,0,8938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21759,1171,941,3,18,302,457,57,235,0,381,243,249,252,11,1595,73,3,0,9309
21760,1171,942,3,18,302,488,58,235,0,360,228,234,238,8,1627,77,9,0,8268
21761,1171,943,3,18,302,510,58,235,0,342,223,229,233,8,1569,90,9,0,7782
21762,1171,944,3,18,302,526,55,235,0,316,235,240,242,12,1679,85,9,0,8311
21763,1171,949,3,18,302,581,53,235,0,204,232,236,237,9,1187,76,3,0,0

In [76]:
test = pd.read_csv("/content/test_set.csv")
#test=test.dropna()
#del test["reportingDate"]
#del test["country"]
#del test["region"]
test=Df_Trans(test)
test

,x,y,region,country,reportingDate,cld,dtr,frs,pet,pre,tmn,tmp,tmx,vap,wet,elevation,dominant_land_cover,X5_Ct_2010_Da,X5_Bf_2010_Da
0,0,24,0,11,89,143,115,0,44,4,299,317,343,123,0,87,3,1461,0
1,0,25,0,11,126,135,118,0,43,2,293,315,342,107,0,79,2,1546,0
2,0,25,0,11,47,135,118,0,43,2,293,315,342,107,0,79,2,1546,0
3,0,26,0,11,97,135,118,0,43,2,293,315,342,107,0,79,2,1546,0
4,1,27,0,11,47,145,122,0,44,1,300,319,346,110,0,64,2,1529,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3034,1210,82,1,6,121,406,29,28,18,93,201,185,171,78,258,39,1,1272,350
3035,1211,80,1,6,3,406,29,28,18,93,201,185,171,78,258,39,1,1272,350
3036,1212,143,1,6,15,370,26,111,13,321,118,101,88,33,722,27,3,740,467
3037,1213,1205,1,26,53,210,40,216,1,86,3,3,2,5,296,44,2,323,169
3038,1214,1204,1,26,101,218,35,216,1,111,4,4,4,5,276,37,3,338,139

In [78]:
import xgboost
model = xgboost.XGBClassifier()
model.fit(x,y)
pred = model.predict(test)
print(pred)

sub = pd.read_csv("/content/sample_submission.csv")
sub["lumpy"] = pred

sub
sub.to_csv("sub.csv",index=False)

[1 1 1 ... 1 1 1]